# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: abb326e86ae2f2466e3d14e017a1967cb0d993463b27fb82bbac453ce82403e11e1cfbce6c2bb7aad2a3c91456bbca6822e3ff752a9416293cd773f74bdc81b4

test:
  secret_key_base: cdee9611aafeb8518b9531b16173515cee73eb89140614447c4c69347ae6d1c5c8cbbd5ef4a762897ceb6ad1afb6c2771bf9a00e74b93c3c8598ecc335293bc8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
